version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - ~/.docker/tmp/db:/var/lib/postgresql/data
  doctor_register_api:
    container_name: doctor_register_api
    build: .
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rails s -p ${RAILS_PORT} -b ${RAILS_BIND}
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    env_file:
      - '.env'
    depends_on:
      - db
    volumes:
      - .:/${COMPOSE_PROJECT_NAME}
